/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  "index": {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils","@herocn/ui"],
    files: [],
    component: null,
  },
  "style": {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils","@herocn/ui"],
    files: [],
    component: null,
  },
  "avatar": {
    name: "avatar",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/avatar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/avatar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button": {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge": {
    name: "badge",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible": {
    name: "collapsible",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/collapsible.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/collapsible.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/dropdown-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/dropdown-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "surface": {
    name: "surface",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/surface.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/surface.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input": {
    name: "input",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/input.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-variants": {
    name: "button-variants",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-sizes": {
    name: "button-sizes",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-sizes.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-sizes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-icons": {
    name: "button-icons",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-rtl": {
    name: "button-rtl",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-basic": {
    name: "collapsible-basic",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-settings": {
    name: "collapsible-settings",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-settings.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-settings.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-file-tree": {
    name: "collapsible-file-tree",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-file-tree.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-file-tree.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-basic": {
    name: "dropdown-menu-basic",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-submenu": {
    name: "dropdown-menu-submenu",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-submenu.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-submenu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-shortcuts": {
    name: "dropdown-menu-shortcuts",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-shortcuts.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-shortcuts.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-icons": {
    name: "dropdown-menu-icons",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-checkboxes": {
    name: "dropdown-menu-checkboxes",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-checkboxes.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-checkboxes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-checkboxes-icons": {
    name: "dropdown-menu-checkboxes-icons",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-checkboxes-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-checkboxes-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-radio-group": {
    name: "dropdown-menu-radio-group",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-radio-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-radio-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-radio-icons": {
    name: "dropdown-menu-radio-icons",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-radio-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-radio-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-destructive": {
    name: "dropdown-menu-destructive",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-destructive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-destructive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-avatar": {
    name: "dropdown-menu-avatar",
    type: "registry:example",
    registryDependencies: ["avatar","button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-avatar.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-avatar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-complex": {
    name: "dropdown-menu-complex",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-complex.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-complex.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-demo": {
    name: "avatar-demo",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-basic": {
    name: "avatar-basic",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-badge": {
    name: "avatar-badge",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-badge.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-badge-icon": {
    name: "avatar-badge-icon",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-badge-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-badge-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-group": {
    name: "avatar-group",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-group-count": {
    name: "avatar-group-count",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-group-count.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-group-count.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-group-count-icon": {
    name: "avatar-group-count-icon",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-group-count-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-group-count-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-size": {
    name: "avatar-size",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-size.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-size.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-dropdown": {
    name: "avatar-dropdown",
    type: "registry:example",
    registryDependencies: ["avatar","button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-dropdown.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-demo": {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-variants": {
    name: "badge-variants",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-sizes": {
    name: "badge-sizes",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-sizes.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-sizes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-icon": {
    name: "badge-icon",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-colors": {
    name: "badge-colors",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-colors.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-colors.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "surface-demo": {
    name: "surface-demo",
    type: "registry:example",
    registryDependencies: ["surface"],
    files: [{
      path: "src/registry/new-york-v4/examples/surface-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/surface-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "surface-variants": {
    name: "surface-variants",
    type: "registry:example",
    registryDependencies: ["surface"],
    files: [{
      path: "src/registry/new-york-v4/examples/surface-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/surface-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-demo": {
    name: "input-demo",
    type: "registry:example",
    registryDependencies: ["input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-variants": {
    name: "input-variants",
    type: "registry:example",
    registryDependencies: ["input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-states": {
    name: "input-states",
    type: "registry:example",
    registryDependencies: ["input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-states.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-states.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-field": {
    name: "input-field",
    type: "registry:example",
    registryDependencies: ["field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-field.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-field.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-fieldgroup": {
    name: "input-fieldgroup",
    type: "registry:example",
    registryDependencies: ["button","field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-fieldgroup.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-fieldgroup.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-badge": {
    name: "input-badge",
    type: "registry:example",
    registryDependencies: ["badge","field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-badge.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-input-group": {
    name: "input-input-group",
    type: "registry:example",
    registryDependencies: ["field","input","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-input-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-input-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-button-group": {
    name: "input-button-group",
    type: "registry:example",
    registryDependencies: ["button","button-group","field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-button-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-button-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  }