/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  "index": {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils","@herocn/ui"],
    files: [],
    component: null,
  },
  "style": {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils","@herocn/ui"],
    files: [],
    component: null,
  },
  "avatar": {
    name: "avatar",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/avatar.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/avatar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button": {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group": {
    name: "button-group",
    type: "registry:ui",
    registryDependencies: ["@herocn/separator"],
    files: [{
      path: "src/registry/new-york-v4/ui/button-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge": {
    name: "badge",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/badge.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card": {
    name: "card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/card.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/card.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible": {
    name: "collapsible",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/collapsible.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/collapsible.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover": {
    name: "popover",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/popover.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/popover.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/dropdown-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/dropdown-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "surface": {
    name: "surface",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/surface.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/surface.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input": {
    name: "input",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/input.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group": {
    name: "input-group",
    type: "registry:ui",
    registryDependencies: ["@herocn/button","@herocn/input","@herocn/textarea"],
    files: [{
      path: "src/registry/new-york-v4/ui/input-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/input-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select": {
    name: "select",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/select.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/select.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator": {
    name: "separator",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/separator.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/separator.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs": {
    name: "tabs",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/tabs.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle": {
    name: "toggle",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/toggle.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/toggle.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea": {
    name: "textarea",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [{
      path: "src/registry/new-york-v4/ui/textarea.tsx",
      type: "registry:ui",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/textarea.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card-demo": {
    name: "card-demo",
    type: "registry:example",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "src/registry/new-york-v4/examples/card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/card-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card-variants": {
    name: "card-variants",
    type: "registry:example",
    registryDependencies: ["card"],
    files: [{
      path: "src/registry/new-york-v4/examples/card-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/card-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card-small": {
    name: "card-small",
    type: "registry:example",
    registryDependencies: ["card"],
    files: [{
      path: "src/registry/new-york-v4/examples/card-small.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/card-small.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card-image": {
    name: "card-image",
    type: "registry:example",
    registryDependencies: ["badge","button","card"],
    files: [{
      path: "src/registry/new-york-v4/examples/card-image.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/card-image.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "card-rtl": {
    name: "card-rtl",
    type: "registry:example",
    registryDependencies: ["button","card","input","label"],
    files: [{
      path: "src/registry/new-york-v4/examples/card-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/card-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-variants": {
    name: "button-variants",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-sizes": {
    name: "button-sizes",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-sizes.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-sizes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-icons": {
    name: "button-icons",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-rtl": {
    name: "button-rtl",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-rtl": {
    name: "badge-rtl",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-rtl": {
    name: "input-rtl",
    type: "registry:example",
    registryDependencies: ["field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea-demo": {
    name: "textarea-demo",
    type: "registry:example",
    registryDependencies: ["textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/textarea-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/textarea-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea-variants": {
    name: "textarea-variants",
    type: "registry:example",
    registryDependencies: ["textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/textarea-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/textarea-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea-states": {
    name: "textarea-states",
    type: "registry:example",
    registryDependencies: ["textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/textarea-states.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/textarea-states.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea-field": {
    name: "textarea-field",
    type: "registry:example",
    registryDependencies: ["field","textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/textarea-field.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/textarea-field.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea-button": {
    name: "textarea-button",
    type: "registry:example",
    registryDependencies: ["button","textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/textarea-button.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/textarea-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea-rtl": {
    name: "textarea-rtl",
    type: "registry:example",
    registryDependencies: ["field","textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/textarea-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/textarea-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "textarea-in-surface": {
    name: "textarea-in-surface",
    type: "registry:example",
    registryDependencies: ["button","card","field","textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/textarea-in-surface.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/textarea-in-surface.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-rtl": {
    name: "avatar-rtl",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-rtl": {
    name: "collapsible-rtl",
    type: "registry:example",
    registryDependencies: ["button","card","collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-rtl": {
    name: "dropdown-menu-rtl",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "surface-rtl": {
    name: "surface-rtl",
    type: "registry:example",
    registryDependencies: ["surface"],
    files: [{
      path: "src/registry/new-york-v4/examples/surface-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/surface-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-demo": {
    name: "collapsible-demo",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-basic": {
    name: "collapsible-basic",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-settings": {
    name: "collapsible-settings",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-settings.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-settings.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "collapsible-file-tree": {
    name: "collapsible-file-tree",
    type: "registry:example",
    registryDependencies: ["collapsible"],
    files: [{
      path: "src/registry/new-york-v4/examples/collapsible-file-tree.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/collapsible-file-tree.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-demo": {
    name: "dropdown-menu-demo",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-basic": {
    name: "dropdown-menu-basic",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-submenu": {
    name: "dropdown-menu-submenu",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-submenu.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-submenu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-shortcuts": {
    name: "dropdown-menu-shortcuts",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-shortcuts.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-shortcuts.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-icons": {
    name: "dropdown-menu-icons",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-checkboxes": {
    name: "dropdown-menu-checkboxes",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-checkboxes.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-checkboxes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-checkboxes-icons": {
    name: "dropdown-menu-checkboxes-icons",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-checkboxes-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-checkboxes-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-radio-group": {
    name: "dropdown-menu-radio-group",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-radio-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-radio-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-radio-icons": {
    name: "dropdown-menu-radio-icons",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-radio-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-radio-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-destructive": {
    name: "dropdown-menu-destructive",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-destructive.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-destructive.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-avatar": {
    name: "dropdown-menu-avatar",
    type: "registry:example",
    registryDependencies: ["avatar","button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-avatar.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-avatar.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "dropdown-menu-complex": {
    name: "dropdown-menu-complex",
    type: "registry:example",
    registryDependencies: ["button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/dropdown-menu-complex.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/dropdown-menu-complex.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-demo": {
    name: "avatar-demo",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-basic": {
    name: "avatar-basic",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-badge": {
    name: "avatar-badge",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-badge.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-badge-icon": {
    name: "avatar-badge-icon",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-badge-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-badge-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-group": {
    name: "avatar-group",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-group-count": {
    name: "avatar-group-count",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-group-count.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-group-count.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-group-count-icon": {
    name: "avatar-group-count-icon",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-group-count-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-group-count-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-size": {
    name: "avatar-size",
    type: "registry:example",
    registryDependencies: ["avatar"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-size.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-size.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "avatar-dropdown": {
    name: "avatar-dropdown",
    type: "registry:example",
    registryDependencies: ["avatar","button","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/avatar-dropdown.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/avatar-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-demo": {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-variants": {
    name: "badge-variants",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-sizes": {
    name: "badge-sizes",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-sizes.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-sizes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-icon": {
    name: "badge-icon",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "badge-colors": {
    name: "badge-colors",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [{
      path: "src/registry/new-york-v4/examples/badge-colors.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/badge-colors.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "surface-demo": {
    name: "surface-demo",
    type: "registry:example",
    registryDependencies: ["surface"],
    files: [{
      path: "src/registry/new-york-v4/examples/surface-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/surface-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "surface-variants": {
    name: "surface-variants",
    type: "registry:example",
    registryDependencies: ["surface"],
    files: [{
      path: "src/registry/new-york-v4/examples/surface-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/surface-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-demo": {
    name: "input-demo",
    type: "registry:example",
    registryDependencies: ["input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-variants": {
    name: "input-variants",
    type: "registry:example",
    registryDependencies: ["input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-states": {
    name: "input-states",
    type: "registry:example",
    registryDependencies: ["input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-states.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-states.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-field": {
    name: "input-field",
    type: "registry:example",
    registryDependencies: ["field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-field.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-field.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-fieldgroup": {
    name: "input-fieldgroup",
    type: "registry:example",
    registryDependencies: ["button","field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-fieldgroup.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-fieldgroup.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-badge": {
    name: "input-badge",
    type: "registry:example",
    registryDependencies: ["badge","field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-badge.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-input-group": {
    name: "input-input-group",
    type: "registry:example",
    registryDependencies: ["field","input","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-input-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-input-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-button-group": {
    name: "input-button-group",
    type: "registry:example",
    registryDependencies: ["button","button-group","field","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-button-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-button-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-demo": {
    name: "button-group-demo",
    type: "registry:example",
    registryDependencies: ["button","button-group","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-orientation": {
    name: "button-group-orientation",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-orientation.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-orientation.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-size": {
    name: "button-group-size",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-size.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-size.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-separator": {
    name: "button-group-separator",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-separator.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-separator.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-split": {
    name: "button-group-split",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-split.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-split.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-input": {
    name: "button-group-input",
    type: "registry:example",
    registryDependencies: ["button","button-group","input"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-input.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-input.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-input-group": {
    name: "button-group-input-group",
    type: "registry:example",
    registryDependencies: ["button","button-group","input-group","tooltip"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-input-group.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-input-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-dropdown": {
    name: "button-group-dropdown",
    type: "registry:example",
    registryDependencies: ["button","button-group","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-dropdown.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-select": {
    name: "button-group-select",
    type: "registry:example",
    registryDependencies: ["button","button-group","input","select"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-select.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-select.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-popover": {
    name: "button-group-popover",
    type: "registry:example",
    registryDependencies: ["button","button-group","field","popover","textarea"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-popover.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-popover.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-rtl": {
    name: "button-group-rtl",
    type: "registry:example",
    registryDependencies: ["button","button-group","dropdown-menu"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "button-group-text": {
    name: "button-group-text",
    type: "registry:example",
    registryDependencies: ["button-group","input","label"],
    files: [{
      path: "src/registry/new-york-v4/examples/button-group-text.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/button-group-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs-demo": {
    name: "tabs-demo",
    type: "registry:example",
    registryDependencies: ["card","tabs"],
    files: [{
      path: "src/registry/new-york-v4/examples/tabs-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/tabs-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs-line": {
    name: "tabs-line",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "src/registry/new-york-v4/examples/tabs-line.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/tabs-line.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs-vertical": {
    name: "tabs-vertical",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "src/registry/new-york-v4/examples/tabs-vertical.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/tabs-vertical.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs-vertical-line": {
    name: "tabs-vertical-line",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "src/registry/new-york-v4/examples/tabs-vertical-line.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/tabs-vertical-line.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs-disabled": {
    name: "tabs-disabled",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "src/registry/new-york-v4/examples/tabs-disabled.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/tabs-disabled.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs-icons": {
    name: "tabs-icons",
    type: "registry:example",
    registryDependencies: ["tabs"],
    files: [{
      path: "src/registry/new-york-v4/examples/tabs-icons.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/tabs-icons.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "tabs-rtl": {
    name: "tabs-rtl",
    type: "registry:example",
    registryDependencies: ["card","tabs"],
    files: [{
      path: "src/registry/new-york-v4/examples/tabs-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/tabs-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-demo": {
    name: "select-demo",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-variants": {
    name: "select-variants",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-surface": {
    name: "select-surface",
    type: "registry:example",
    registryDependencies: ["select","surface"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-surface.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-surface.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-groups": {
    name: "select-groups",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-groups.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-groups.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-multiple": {
    name: "select-multiple",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-multiple.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-multiple.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-scrollable": {
    name: "select-scrollable",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-scrollable.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-scrollable.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-disabled": {
    name: "select-disabled",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-disabled.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-disabled.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-invalid": {
    name: "select-invalid",
    type: "registry:example",
    registryDependencies: ["field","select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-invalid.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-invalid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "select-rtl": {
    name: "select-rtl",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [{
      path: "src/registry/new-york-v4/examples/select-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/select-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator-demo": {
    name: "separator-demo",
    type: "registry:example",
    registryDependencies: ["separator"],
    files: [{
      path: "src/registry/new-york-v4/examples/separator-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/separator-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator-vertical": {
    name: "separator-vertical",
    type: "registry:example",
    registryDependencies: ["separator"],
    files: [{
      path: "src/registry/new-york-v4/examples/separator-vertical.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/separator-vertical.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator-menu": {
    name: "separator-menu",
    type: "registry:example",
    registryDependencies: ["separator"],
    files: [{
      path: "src/registry/new-york-v4/examples/separator-menu.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/separator-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator-list": {
    name: "separator-list",
    type: "registry:example",
    registryDependencies: ["separator"],
    files: [{
      path: "src/registry/new-york-v4/examples/separator-list.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/separator-list.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator-surface": {
    name: "separator-surface",
    type: "registry:example",
    registryDependencies: ["separator","surface"],
    files: [{
      path: "src/registry/new-york-v4/examples/separator-surface.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/separator-surface.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "separator-rtl": {
    name: "separator-rtl",
    type: "registry:example",
    registryDependencies: ["separator"],
    files: [{
      path: "src/registry/new-york-v4/examples/separator-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/separator-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover-demo": {
    name: "popover-demo",
    type: "registry:example",
    registryDependencies: ["button","input","label","popover"],
    files: [{
      path: "src/registry/new-york-v4/examples/popover-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/popover-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover-basic": {
    name: "popover-basic",
    type: "registry:example",
    registryDependencies: ["button","popover"],
    files: [{
      path: "src/registry/new-york-v4/examples/popover-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/popover-basic.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover-align": {
    name: "popover-align",
    type: "registry:example",
    registryDependencies: ["button","popover"],
    files: [{
      path: "src/registry/new-york-v4/examples/popover-align.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/popover-align.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover-form": {
    name: "popover-form",
    type: "registry:example",
    registryDependencies: ["button","field","input","popover"],
    files: [{
      path: "src/registry/new-york-v4/examples/popover-form.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/popover-form.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover-with-arrow": {
    name: "popover-with-arrow",
    type: "registry:example",
    registryDependencies: ["button","popover"],
    files: [{
      path: "src/registry/new-york-v4/examples/popover-with-arrow.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/popover-with-arrow.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "popover-rtl": {
    name: "popover-rtl",
    type: "registry:example",
    registryDependencies: ["button","popover"],
    files: [{
      path: "src/registry/new-york-v4/examples/popover-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/popover-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-demo": {
    name: "input-group-demo",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-variants": {
    name: "input-group-variants",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-variants.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-variants.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-invalid": {
    name: "input-group-invalid",
    type: "registry:example",
    registryDependencies: ["field","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-invalid.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-invalid.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-inline-start": {
    name: "input-group-inline-start",
    type: "registry:example",
    registryDependencies: ["field","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-inline-start.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-inline-start.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-inline-end": {
    name: "input-group-inline-end",
    type: "registry:example",
    registryDependencies: ["field","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-inline-end.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-inline-end.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-block-start": {
    name: "input-group-block-start",
    type: "registry:example",
    registryDependencies: ["field","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-block-start.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-block-start.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-block-end": {
    name: "input-group-block-end",
    type: "registry:example",
    registryDependencies: ["field","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-block-end.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-block-end.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-icon": {
    name: "input-group-icon",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-icon.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-text": {
    name: "input-group-text",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-text.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-button": {
    name: "input-group-button",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-button.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-spinner": {
    name: "input-group-spinner",
    type: "registry:example",
    registryDependencies: ["input-group","spinner"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-spinner.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-spinner.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-textarea": {
    name: "input-group-textarea",
    type: "registry:example",
    registryDependencies: ["input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-textarea.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-textarea.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-dropdown": {
    name: "input-group-dropdown",
    type: "registry:example",
    registryDependencies: ["dropdown-menu","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-dropdown.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-dropdown.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-rtl": {
    name: "input-group-rtl",
    type: "registry:example",
    registryDependencies: ["field","input-group","spinner"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "input-group-in-surface": {
    name: "input-group-in-surface",
    type: "registry:example",
    registryDependencies: ["card","input-group"],
    files: [{
      path: "src/registry/new-york-v4/examples/input-group-in-surface.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/input-group-in-surface.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle-demo": {
    name: "toggle-demo",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{
      path: "src/registry/new-york-v4/examples/toggle-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/toggle-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle-ghost": {
    name: "toggle-ghost",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{
      path: "src/registry/new-york-v4/examples/toggle-ghost.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/toggle-ghost.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle-sizes": {
    name: "toggle-sizes",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{
      path: "src/registry/new-york-v4/examples/toggle-sizes.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/toggle-sizes.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle-disabled": {
    name: "toggle-disabled",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{
      path: "src/registry/new-york-v4/examples/toggle-disabled.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/toggle-disabled.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  "toggle-rtl": {
    name: "toggle-rtl",
    type: "registry:example",
    registryDependencies: ["toggle"],
    files: [{
      path: "src/registry/new-york-v4/examples/toggle-rtl.tsx",
      type: "registry:example",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/examples/toggle-rtl.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
  },
  }